-- Complete Brazilian Casino Information
-- All data focused on Brazilian market with BRL currency support

-- Clear existing casino info data for these casinos
DELETE FROM casino_info WHERE casino_id IN (
    SELECT id FROM casinos WHERE slug IN (
        'betwinner', '22bet', 'betano', 'bet365', '1xbet', 'estrela-bet',
        'blaze', 'br4bet', 'lottoland', 'seguro-bet', 'bateu-bet', 'brazino777'
    )
);

-- 1. BETWINNER - Complete Information
INSERT INTO casino_info (casino_id, language, 
    company_info, established_year, licenses_safety, operating_countries,
    supported_currencies, supported_languages, game_types, payment_methods,
    mobile_apps, customer_support,
    why_choose, casino_features, licenses_safety_detail, operating_countries_detail,
    game_variety_detail, sports_betting_features, special_promotions, suitable_players
) VALUES
-- Betwinner English
((SELECT id FROM casinos WHERE slug = 'betwinner'), 'en',
    'Marikit Holdings Ltd', '2018', 'Curacao eGaming License', 'Brazil, India, Africa, Asia',
    'BRL, USD, EUR, BTC, ETH', 'Portuguese, English, Spanish', 'Sports, Casino, Live Dealer, Esports', 
    'PIX, Boleto, Credit Cards, Crypto, eWallets', 'Android, iOS', '24/7 Live Chat, Email',
    'High odds, extensive sports coverage, cryptocurrency support, and instant PIX payments',
    'Over 1000+ daily sports events, 200+ casino providers, live streaming, cash out option',
    'Licensed by Curacao eGaming Authority (License No. 8048/JAZ), SSL encryption, responsible gaming tools',
    'Operates legally in Brazil under international license, serves over 50 countries worldwide',
    'Sports betting, slots, table games, live casino, virtual sports, TV games, lottery, toto',
    'Pre-match and live betting, bet builder, cash out, live streaming, statistics center, multi-bet options',
    '200% first deposit bonus up to R$1,700, weekly reload bonuses, accumulator boost, cashback program',
    'Perfect for sports enthusiasts, crypto users, and players seeking variety with Brazilian payment methods'
),
-- Betwinner Portuguese
((SELECT id FROM casinos WHERE slug = 'betwinner'), 'pt',
    'Marikit Holdings Ltd', '2018', 'Licença Curacao eGaming', 'Brasil, Índia, África, Ásia',
    'BRL, USD, EUR, BTC, ETH', 'Português, Inglês, Espanhol', 'Esportes, Cassino, Dealer ao Vivo, Esports',
    'PIX, Boleto, Cartões de Crédito, Cripto, Carteiras Eletrônicas', 'Android, iOS', 'Chat ao Vivo 24/7, Email',
    'Odds elevadas, ampla cobertura esportiva, suporte a criptomoedas e pagamentos PIX instantâneos',
    'Mais de 1000+ eventos esportivos diários, 200+ provedores de cassino, transmissão ao vivo, opção de saque',
    'Licenciado pela Curacao eGaming Authority (Licença No. 8048/JAZ), criptografia SSL, ferramentas de jogo responsável',
    'Opera legalmente no Brasil sob licença internacional, atende mais de 50 países em todo o mundo',
    'Apostas esportivas, slots, jogos de mesa, cassino ao vivo, esportes virtuais, jogos de TV, loteria, toto',
    'Apostas pré-jogo e ao vivo, criador de apostas, saque, transmissão ao vivo, centro de estatísticas, opções multi-apostas',
    'Bônus de 200% no primeiro depósito até R$1.700, bônus de recarga semanais, boost de acumuladas, programa de cashback',
    'Perfeito para entusiastas de esportes, usuários de cripto e jogadores que buscam variedade com métodos de pagamento brasileiros'
),
-- Betwinner Chinese
((SELECT id FROM casinos WHERE slug = 'betwinner'), 'zh',
    'Marikit Holdings Ltd', '2018', '庫拉索電子遊戲許可證', '巴西、印度、非洲、亞洲',
    'BRL, USD, EUR, BTC, ETH', '葡萄牙語、英語、西班牙語', '體育、賭場、真人荷官、電競',
    'PIX、Boleto、信用卡、加密貨幣、電子錢包', 'Android、iOS', '24/7即時聊天、電子郵件',
    '高賠率、廣泛的體育賽事覆蓋、支援加密貨幣和即時PIX支付',
    '每日超過1000+體育賽事、200+賭場供應商、即時串流、提前兌現選項',
    '由庫拉索電子遊戲管理局授權（許可證號8048/JAZ）、SSL加密、負責任遊戲工具',
    '在國際許可證下合法運營於巴西，服務全球超過50個國家',
    '體育博彩、老虎機、桌上遊戲、真人賭場、虛擬體育、電視遊戲、彩票、足彩',
    '賽前和滾球投注、投注構建器、提前兌現、即時串流、統計中心、多重投注選項',
    '首存200%獎金高達R$1,700、每週充值獎金、串關加成、返水計劃',
    '適合體育愛好者、加密貨幣用戶和尋求多樣性的巴西支付方式玩家'
),

-- 2. 22BET - Complete Information
((SELECT id FROM casinos WHERE slug = '22bet'), 'en',
    'TechSolutions Group N.V.', '2017', 'Curacao License', 'Brazil, Africa, Asia, Europe',
    'BRL, USD, EUR, INR, NGN', 'Portuguese, English, Spanish, French', 'Sports, Casino, Live Casino, Esports',
    'PIX, Boleto, Visa, Mastercard, Skrill, Neteller', 'Android, iOS', '24/7 Support via Live Chat',
    'Competitive odds, huge game selection, fast payouts, and excellent mobile experience',
    'Over 1000 games, 40+ sports, live betting, virtual sports, fast withdrawals',
    'Licensed and regulated by Curacao Gaming Authority, secure SSL encryption',
    'Available in Brazil and over 100 countries, focused on emerging markets',
    'Slots, table games, live dealers, sports betting, virtual sports, esports, lottery',
    'Live betting, multi-live, bet constructor, statistics, live scores, streaming on selected events',
    '100% welcome bonus up to R$650, Friday reload bonus, weekly rebate, birthday bonus',
    'Ideal for players who want variety, sports bettors, and mobile gaming enthusiasts'
),
((SELECT id FROM casinos WHERE slug = '22bet'), 'pt',
    'TechSolutions Group N.V.', '2017', 'Licença de Curaçao', 'Brasil, África, Ásia, Europa',
    'BRL, USD, EUR, INR, NGN', 'Português, Inglês, Espanhol, Francês', 'Esportes, Cassino, Cassino ao Vivo, Esports',
    'PIX, Boleto, Visa, Mastercard, Skrill, Neteller', 'Android, iOS', 'Suporte 24/7 via Chat ao Vivo',
    'Odds competitivas, enorme seleção de jogos, pagamentos rápidos e excelente experiência móvel',
    'Mais de 1000 jogos, 40+ esportes, apostas ao vivo, esportes virtuais, saques rápidos',
    'Licenciado e regulamentado pela Curacao Gaming Authority, criptografia SSL segura',
    'Disponível no Brasil e em mais de 100 países, focado em mercados emergentes',
    'Slots, jogos de mesa, dealers ao vivo, apostas esportivas, esportes virtuais, esports, loteria',
    'Apostas ao vivo, multi-ao vivo, construtor de apostas, estatísticas, placares ao vivo, streaming em eventos selecionados',
    'Bônus de boas-vindas de 100% até R$650, bônus de recarga sexta-feira, rebate semanal, bônus de aniversário',
    'Ideal para jogadores que querem variedade, apostadores esportivos e entusiastas de jogos móveis'
),
((SELECT id FROM casinos WHERE slug = '22bet'), 'zh',
    'TechSolutions Group N.V.', '2017', '庫拉索許可證', '巴西、非洲、亞洲、歐洲',
    'BRL, USD, EUR, INR, NGN', '葡萄牙語、英語、西班牙語、法語', '體育、賭場、真人賭場、電競',
    'PIX、Boleto、Visa、Mastercard、Skrill、Neteller', 'Android、iOS', '24/7即時聊天支援',
    '競爭力賠率、龐大遊戲選擇、快速支付和優秀的移動體驗',
    '超過1000個遊戲、40+體育項目、滾球投注、虛擬體育、快速提款',
    '由庫拉索遊戲管理局許可和監管、安全SSL加密',
    '在巴西和超過100個國家可用、專注於新興市場',
    '老虎機、桌上遊戲、真人荷官、體育博彩、虛擬體育、電競、彩票',
    '滾球投注、多重滾球、投注構建器、統計數據、即時比分、部分賽事串流',
    '100%歡迎獎金高達R$650、週五充值獎金、每週返利、生日獎金',
    '適合想要多樣性的玩家、體育投注者和移動遊戲愛好者'
),

-- 3. BETANO - Complete Information
((SELECT id FROM casinos WHERE slug = 'betano'), 'en',
    'Kaizen Gaming International Ltd', '2018', 'MGA License, Brazil License', 'Brazil, Portugal, Germany, Romania',
    'BRL, EUR', 'Portuguese, English', 'Sports Betting, Casino, Live Casino',
    'PIX, Bank Transfer, Visa, Mastercard', 'Android, iOS', '24/7 Portuguese Support',
    'Official Brazilian license, excellent odds, local payment methods, Portuguese support',
    'Licensed in Brazil, extensive football coverage, live streaming, Super Odds daily',
    'Malta Gaming Authority License (MGA/B2C/209/2011), Brazilian federal license',
    'Legally operating in Brazil with federal authorization, also in European markets',
    'Football, basketball, tennis, MMA, volleyball, esports, casino games, live dealers',
    'Live betting, Super Odds, Bet Mentor, Cash Out, Edit Bet, live statistics',
    'Welcome bonus up to R$500, free bets, missions with rewards, odds boosts',
    'Perfect for Brazilian players seeking legal, safe betting with local support'
),
((SELECT id FROM casinos WHERE slug = 'betano'), 'pt',
    'Kaizen Gaming International Ltd', '2018', 'Licença MGA, Licença Brasil', 'Brasil, Portugal, Alemanha, Romênia',
    'BRL, EUR', 'Português, Inglês', 'Apostas Esportivas, Cassino, Cassino ao Vivo',
    'PIX, Transferência Bancária, Visa, Mastercard', 'Android, iOS', 'Suporte em Português 24/7',
    'Licença oficial brasileira, excelentes odds, métodos de pagamento locais, suporte em português',
    'Licenciado no Brasil, ampla cobertura de futebol, transmissão ao vivo, Super Odds diárias',
    'Licença da Malta Gaming Authority (MGA/B2C/209/2011), licença federal brasileira',
    'Operando legalmente no Brasil com autorização federal, também em mercados europeus',
    'Futebol, basquete, tênis, MMA, vôlei, esports, jogos de cassino, dealers ao vivo',
    'Apostas ao vivo, Super Odds, Bet Mentor, Cash Out, Editar Aposta, estatísticas ao vivo',
    'Bônus de boas-vindas até R$500, apostas grátis, missões com recompensas, odds aumentadas',
    'Perfeito para jogadores brasileiros que buscam apostas legais e seguras com suporte local'
),
((SELECT id FROM casinos WHERE slug = 'betano'), 'zh',
    'Kaizen Gaming International Ltd', '2018', 'MGA許可證、巴西許可證', '巴西、葡萄牙、德國、羅馬尼亞',
    'BRL, EUR', '葡萄牙語、英語', '體育博彩、賭場、真人賭場',
    'PIX、銀行轉帳、Visa、Mastercard', 'Android、iOS', '24/7葡萄牙語支援',
    '官方巴西許可證、優秀賠率、本地支付方式、葡萄牙語支援',
    '在巴西獲得許可、廣泛的足球覆蓋、即時串流、每日超級賠率',
    '馬耳他遊戲管理局許可證（MGA/B2C/209/2011）、巴西聯邦許可證',
    '在巴西合法運營並獲得聯邦授權、也在歐洲市場運營',
    '足球、籃球、網球、MMA、排球、電競、賭場遊戲、真人荷官',
    '滾球投注、超級賠率、投注導師、提前兌現、編輯投注、即時統計',
    '歡迎獎金高達R$500、免費投注、任務獎勵、賠率提升',
    '適合尋求合法、安全投注且有本地支援的巴西玩家'
),

-- 4. BET365 - Complete Information
((SELECT id FROM casinos WHERE slug = 'bet365'), 'en',
    'Hillside (New Media) Limited', '2000', 'UK Gambling Commission, MGA', 'Brazil, UK, Australia, USA (selected states)',
    'BRL, USD, EUR, GBP, AUD', 'Portuguese, English, Spanish', 'Sports, Casino, Poker, Bingo',
    'PIX, Bank Transfer, Credit/Debit Cards', 'Android, iOS', '24/7 Multilingual Support',
    'World leading sportsbook, live streaming, early payout, extensive markets',
    '40,000+ live events monthly, 200+ payment methods, live streaming, bet builder',
    'UK Gambling Commission (License 55148), Malta Gaming Authority, multiple international licenses',
    'Operating in Brazil, available in over 200 countries worldwide',
    'All major sports, esports, casino, live casino, poker, bingo, virtual sports',
    'Early payout, bet builder, cash out, live streaming, statistics, in-play betting',
    'Up to R$200 in bet credits for new customers, bore draw money back, accumulator bonus',
    'Ideal for serious sports bettors, live betting enthusiasts, and professional gamblers'
),
((SELECT id FROM casinos WHERE slug = 'bet365'), 'pt',
    'Hillside (New Media) Limited', '2000', 'UK Gambling Commission, MGA', 'Brasil, Reino Unido, Austrália, EUA (estados selecionados)',
    'BRL, USD, EUR, GBP, AUD', 'Português, Inglês, Espanhol', 'Esportes, Cassino, Pôquer, Bingo',
    'PIX, Transferência Bancária, Cartões de Crédito/Débito', 'Android, iOS', 'Suporte Multilíngue 24/7',
    'Casa de apostas líder mundial, transmissão ao vivo, pagamento antecipado, mercados extensos',
    '40.000+ eventos ao vivo mensais, 200+ métodos de pagamento, transmissão ao vivo, criador de apostas',
    'UK Gambling Commission (Licença 55148), Malta Gaming Authority, múltiplas licenças internacionais',
    'Operando no Brasil, disponível em mais de 200 países em todo o mundo',
    'Todos os principais esportes, esports, cassino, cassino ao vivo, pôquer, bingo, esportes virtuais',
    'Pagamento antecipado, criador de apostas, cash out, transmissão ao vivo, estatísticas, apostas ao vivo',
    'Até R$200 em créditos de aposta para novos clientes, devolução em empate sem gols, bônus de acumuladas',
    'Ideal para apostadores esportivos sérios, entusiastas de apostas ao vivo e jogadores profissionais'
),
((SELECT id FROM casinos WHERE slug = 'bet365'), 'zh',
    'Hillside (New Media) Limited', '2000', '英國博彩委員會、MGA', '巴西、英國、澳大利亞、美國（部分州）',
    'BRL, USD, EUR, GBP, AUD', '葡萄牙語、英語、西班牙語', '體育、賭場、撲克、賓果',
    'PIX、銀行轉帳、信用卡/借記卡', 'Android、iOS', '24/7多語言支援',
    '世界領先的體育博彩公司、即時串流、提前派彩、廣泛市場',
    '每月40,000+現場賽事、200+支付方式、即時串流、投注構建器',
    '英國博彩委員會（許可證55148）、馬耳他遊戲管理局、多個國際許可證',
    '在巴西運營、在全球超過200個國家可用',
    '所有主要體育項目、電競、賭場、真人賭場、撲克、賓果、虛擬體育',
    '提前派彩、投注構建器、提前兌現、即時串流、統計數據、滾球投注',
    '新客戶高達R$200投注積分、悶平退款、串關獎金',
    '適合認真的體育投注者、滾球投注愛好者和職業賭徒'
),

-- 5. 1xBET - Complete Information
((SELECT id FROM casinos WHERE slug = '1xbet'), 'en',
    'DEFY LTDA (Brazil)', '2007', 'Curacao License, Brazilian Authorization', 'Brazil, Africa, Asia, Eastern Europe',
    'BRL, USD, EUR, BTC, USDT', 'Portuguese, English, Spanish', 'Sports, Casino, Live Casino, Virtual Sports',
    'PIX, Boleto, Crypto, eWallets, Cards', 'Android, iOS, Windows', '24/7 Support in Portuguese',
    'Huge selection of sports and markets, high odds, cryptocurrency friendly',
    'Over 1000 daily events, 100+ payment methods, live streaming, one-click bet',
    'Curacao eGaming License, authorized by Brazilian government (SPA)',
    'Legally authorized in Brazil, operates in over 50 countries',
    'Sports betting, live casino, slots, TV games, virtual sports, esports, financial betting',
    'Live streaming, cash out, bet insurance, multi-live, statistics center, bet slip sales',
    'Welcome bonus up to R$1200, advance bet, lucky Friday, accumulator of the day',
    'Perfect for experienced bettors seeking variety and high limits'
),
((SELECT id FROM casinos WHERE slug = '1xbet'), 'pt',
    'DEFY LTDA (Brasil)', '2007', 'Licença Curaçao, Autorização Brasileira', 'Brasil, África, Ásia, Europa Oriental',
    'BRL, USD, EUR, BTC, USDT', 'Português, Inglês, Espanhol', 'Esportes, Cassino, Cassino ao Vivo, Esportes Virtuais',
    'PIX, Boleto, Cripto, Carteiras Eletrônicas, Cartões', 'Android, iOS, Windows', 'Suporte 24/7 em Português',
    'Enorme seleção de esportes e mercados, odds altas, amigável a criptomoedas',
    'Mais de 1000 eventos diários, 100+ métodos de pagamento, transmissão ao vivo, aposta com um clique',
    'Licença Curacao eGaming, autorizado pelo governo brasileiro (SPA)',
    'Legalmente autorizado no Brasil, opera em mais de 50 países',
    'Apostas esportivas, cassino ao vivo, slots, jogos de TV, esportes virtuais, esports, apostas financeiras',
    'Transmissão ao vivo, cash out, seguro de aposta, multi-ao vivo, centro de estatísticas, venda de bilhetes',
    'Bônus de boas-vindas até R$1200, aposta antecipada, sexta-feira da sorte, acumulador do dia',
    'Perfeito para apostadores experientes que buscam variedade e limites altos'
),
((SELECT id FROM casinos WHERE slug = '1xbet'), 'zh',
    'DEFY LTDA（巴西）', '2007', '庫拉索許可證、巴西授權', '巴西、非洲、亞洲、東歐',
    'BRL, USD, EUR, BTC, USDT', '葡萄牙語、英語、西班牙語', '體育、賭場、真人賭場、虛擬體育',
    'PIX、Boleto、加密貨幣、電子錢包、卡片', 'Android、iOS、Windows', '24/7葡萄牙語支援',
    '龐大的體育和市場選擇、高賠率、加密貨幣友好',
    '每日超過1000個賽事、100+支付方式、即時串流、一鍵投注',
    '庫拉索電子遊戲許可證、巴西政府授權（SPA）',
    '在巴西合法授權、在超過50個國家運營',
    '體育博彩、真人賭場、老虎機、電視遊戲、虛擬體育、電競、金融投注',
    '即時串流、提前兌現、投注保險、多重滾球、統計中心、投注單銷售',
    '歡迎獎金高達R$1200、預付投注、幸運星期五、每日串關',
    '適合尋求多樣性和高限額的經驗豐富投注者'
),

-- 6. ESTRELA BET - Complete Information
((SELECT id FROM casinos WHERE slug = 'estrela-bet'), 'en',
    'EstrelaBet Brasil S.A.', '2020', 'Brazilian License', 'Brazil',
    'BRL', 'Portuguese', 'Sports Betting, Casino, Live Casino',
    'PIX, Bank Transfer, Credit Cards', 'Android, iOS', '24/7 Brazilian Support',
    'Local Brazilian brand, instant PIX, Portuguese support, local promotions',
    'Focus on Brazilian sports, local payment methods, responsible gaming tools',
    'Fully licensed by Brazilian government, local regulations compliant',
    'Exclusively operates in Brazil with federal authorization',
    'Football, basketball, volleyball, MMA, tennis, casino games, live dealers',
    'Live betting, cash out, turbinada (boosted odds), statistics, Brazilian championships focus',
    'Welcome bonus, daily promotions, loyalty program, Brazilian holiday specials',
    'Perfect for Brazilian players wanting a local, trusted betting experience'
),
((SELECT id FROM casinos WHERE slug = 'estrela-bet'), 'pt',
    'EstrelaBet Brasil S.A.', '2020', 'Licença Brasileira', 'Brasil',
    'BRL', 'Português', 'Apostas Esportivas, Cassino, Cassino ao Vivo',
    'PIX, Transferência Bancária, Cartões de Crédito', 'Android, iOS', 'Suporte Brasileiro 24/7',
    'Marca brasileira local, PIX instantâneo, suporte em português, promoções locais',
    'Foco em esportes brasileiros, métodos de pagamento locais, ferramentas de jogo responsável',
    'Totalmente licenciado pelo governo brasileiro, em conformidade com regulamentos locais',
    'Opera exclusivamente no Brasil com autorização federal',
    'Futebol, basquete, vôlei, MMA, tênis, jogos de cassino, dealers ao vivo',
    'Apostas ao vivo, cash out, turbinada (odds aumentadas), estatísticas, foco em campeonatos brasileiros',
    'Bônus de boas-vindas, promoções diárias, programa de fidelidade, especiais de feriados brasileiros',
    'Perfeito para jogadores brasileiros que querem uma experiência de apostas local e confiável'
),
((SELECT id FROM casinos WHERE slug = 'estrela-bet'), 'zh',
    'EstrelaBet Brasil S.A.', '2020', '巴西許可證', '巴西',
    'BRL', '葡萄牙語', '體育博彩、賭場、真人賭場',
    'PIX、銀行轉帳、信用卡', 'Android、iOS', '24/7巴西支援',
    '本地巴西品牌、即時PIX、葡萄牙語支援、本地促銷',
    '專注於巴西體育、本地支付方式、負責任遊戲工具',
    '完全獲得巴西政府許可、符合當地法規',
    '僅在巴西運營並獲得聯邦授權',
    '足球、籃球、排球、MMA、網球、賭場遊戲、真人荷官',
    '滾球投注、提前兌現、加速賠率、統計數據、專注巴西錦標賽',
    '歡迎獎金、每日促銷、忠誠計劃、巴西節日特別優惠',
    '適合想要本地、可信投注體驗的巴西玩家'
),

-- 7. BLAZE - Complete Information
((SELECT id FROM casinos WHERE slug = 'blaze'), 'en',
    'Prolific Trade N.V.', '2020', 'Curacao License', 'Brazil, Latin America',
    'BRL, USD, BTC', 'Portuguese, English, Spanish', 'Casino, Crash Games, Sports',
    'PIX, Cryptocurrency, Credit Cards', 'Android, iOS', '24/7 Live Support',
    'Famous for Crash games, instant payments, influencer partnerships',
    'Original Crash, Double, Mines games, sports betting, instant withdrawals',
    'Curacao eGaming License, provably fair games',
    'Popular in Brazil and Latin American markets',
    'Crash, Double, Mines, Dice, Roulette, Slots, Sports betting',
    'Live betting, exclusive Blaze originals, instant bet, auto cash out',
    'Daily bonuses, free spins, cashback, referral program',
    'Ideal for players who enjoy fast-paced games and instant gratification'
),
((SELECT id FROM casinos WHERE slug = 'blaze'), 'pt',
    'Prolific Trade N.V.', '2020', 'Licença Curaçao', 'Brasil, América Latina',
    'BRL, USD, BTC', 'Português, Inglês, Espanhol', 'Cassino, Jogos Crash, Esportes',
    'PIX, Criptomoeda, Cartões de Crédito', 'Android, iOS', 'Suporte ao Vivo 24/7',
    'Famoso por jogos Crash, pagamentos instantâneos, parcerias com influenciadores',
    'Crash original, Double, Mines, apostas esportivas, saques instantâneos',
    'Licença Curacao eGaming, jogos comprovadamente justos',
    'Popular no Brasil e mercados da América Latina',
    'Crash, Double, Mines, Dice, Roleta, Slots, Apostas esportivas',
    'Apostas ao vivo, originais exclusivos Blaze, aposta instantânea, auto cash out',
    'Bônus diários, rodadas grátis, cashback, programa de indicação',
    'Ideal para jogadores que gostam de jogos rápidos e gratificação instantânea'
),
((SELECT id FROM casinos WHERE slug = 'blaze'), 'zh',
    'Prolific Trade N.V.', '2020', '庫拉索許可證', '巴西、拉丁美洲',
    'BRL, USD, BTC', '葡萄牙語、英語、西班牙語', '賭場、Crash遊戲、體育',
    'PIX、加密貨幣、信用卡', 'Android、iOS', '24/7即時支援',
    '以Crash遊戲聞名、即時支付、網紅合作',
    '原創Crash、Double、Mines遊戲、體育博彩、即時提款',
    '庫拉索電子遊戲許可證、可證明公平的遊戲',
    '在巴西和拉丁美洲市場受歡迎',
    'Crash、Double、Mines、骰子、輪盤、老虎機、體育博彩',
    '滾球投注、Blaze獨家原創、即時投注、自動提前兌現',
    '每日獎金、免費旋轉、返水、推薦計劃',
    '適合喜歡快節奏遊戲和即時滿足的玩家'
),

-- 8. BR4BET - Complete Information
((SELECT id FROM casinos WHERE slug = 'br4bet'), 'en',
    'BR4BET Entertainment Ltd', '2023', 'Curacao License', 'Brazil',
    'BRL, USDT', 'Portuguese, English', 'Sports, Casino, Live Games',
    'PIX, Cryptocurrency', 'Web Mobile Optimized', '24/7 Chat Support',
    'New platform focused on Brazilian market, crypto-friendly, modern interface',
    'Sports betting, casino games, fast payouts, mobile optimized',
    'Curacao eGaming License, SSL encryption',
    'Primarily serves Brazilian market',
    'Football, basketball, tennis, esports, slots, table games',
    'Live betting, quick bet, statistics, live scores',
    'Welcome bonus package, weekly cashback, reload bonuses',
    'Good for tech-savvy players and cryptocurrency enthusiasts'
),
((SELECT id FROM casinos WHERE slug = 'br4bet'), 'pt',
    'BR4BET Entertainment Ltd', '2023', 'Licença Curaçao', 'Brasil',
    'BRL, USDT', 'Português, Inglês', 'Esportes, Cassino, Jogos ao Vivo',
    'PIX, Criptomoeda', 'Web Mobile Otimizado', 'Suporte via Chat 24/7',
    'Nova plataforma focada no mercado brasileiro, amigável a cripto, interface moderna',
    'Apostas esportivas, jogos de cassino, pagamentos rápidos, otimizado para mobile',
    'Licença Curacao eGaming, criptografia SSL',
    'Atende principalmente o mercado brasileiro',
    'Futebol, basquete, tênis, esports, slots, jogos de mesa',
    'Apostas ao vivo, aposta rápida, estatísticas, placares ao vivo',
    'Pacote de bônus de boas-vindas, cashback semanal, bônus de recarga',
    'Bom para jogadores experientes em tecnologia e entusiastas de criptomoedas'
),
((SELECT id FROM casinos WHERE slug = 'br4bet'), 'zh',
    'BR4BET Entertainment Ltd', '2023', '庫拉索許可證', '巴西',
    'BRL, USDT', '葡萄牙語、英語', '體育、賭場、真人遊戲',
    'PIX、加密貨幣', '移動網頁優化', '24/7聊天支援',
    '專注於巴西市場的新平台、加密友好、現代界面',
    '體育博彩、賭場遊戲、快速支付、移動優化',
    '庫拉索電子遊戲許可證、SSL加密',
    '主要服務巴西市場',
    '足球、籃球、網球、電競、老虎機、桌上遊戲',
    '滾球投注、快速投注、統計數據、即時比分',
    '歡迎獎金套餐、每週返水、充值獎金',
    '適合精通科技的玩家和加密貨幣愛好者'
),

-- 9. LOTTOLAND - Complete Information
((SELECT id FROM casinos WHERE slug = 'lottoland'), 'en',
    'Lottoland Limited', '2013', 'MGA License, UK License', 'Brazil, UK, Ireland, Australia',
    'BRL, EUR, GBP, AUD', 'Portuguese, English', 'Lottery Betting, Sports, Casino',
    'PIX, Credit Cards, Bank Transfer', 'Android, iOS', '24/7 Customer Service',
    'Unique lottery betting concept, international lotteries access, sports betting',
    'Bet on world lotteries, sports betting, instant win games, casino',
    'Malta Gaming Authority, UK Gambling Commission licensed',
    'Operating legally in Brazil and multiple regulated markets',
    'Lottery betting, sports, instant wins, slots, table games',
    'Live betting, lottery results, syndicate betting, combo bets',
    'Welcome offer, double jackpot promotions, price reductions',
    'Perfect for lottery enthusiasts and casual sports bettors'
),
((SELECT id FROM casinos WHERE slug = 'lottoland'), 'pt',
    'Lottoland Limited', '2013', 'Licença MGA, Licença UK', 'Brasil, Reino Unido, Irlanda, Austrália',
    'BRL, EUR, GBP, AUD', 'Português, Inglês', 'Apostas em Loteria, Esportes, Cassino',
    'PIX, Cartões de Crédito, Transferência Bancária', 'Android, iOS', 'Atendimento ao Cliente 24/7',
    'Conceito único de apostas em loteria, acesso a loterias internacionais, apostas esportivas',
    'Aposte em loterias mundiais, apostas esportivas, jogos de ganho instantâneo, cassino',
    'Malta Gaming Authority, licenciado pela UK Gambling Commission',
    'Operando legalmente no Brasil e múltiplos mercados regulamentados',
    'Apostas em loteria, esportes, ganhos instantâneos, slots, jogos de mesa',
    'Apostas ao vivo, resultados de loteria, apostas em grupo, apostas combinadas',
    'Oferta de boas-vindas, promoções de jackpot duplo, reduções de preço',
    'Perfeito para entusiastas de loteria e apostadores esportivos casuais'
),
((SELECT id FROM casinos WHERE slug = 'lottoland'), 'zh',
    'Lottoland Limited', '2013', 'MGA許可證、英國許可證', '巴西、英國、愛爾蘭、澳大利亞',
    'BRL, EUR, GBP, AUD', '葡萄牙語、英語', '彩票投注、體育、賭場',
    'PIX、信用卡、銀行轉帳', 'Android、iOS', '24/7客戶服務',
    '獨特的彩票投注概念、國際彩票訪問、體育博彩',
    '投注世界彩票、體育博彩、即時贏獎遊戲、賭場',
    '馬耳他遊戲管理局、英國博彩委員會許可',
    '在巴西和多個受監管市場合法運營',
    '彩票投注、體育、即時贏獎、老虎機、桌上遊戲',
    '滾球投注、彩票結果、團體投注、組合投注',
    '歡迎優惠、雙倍頭獎促銷、價格優惠',
    '適合彩票愛好者和休閒體育投注者'
),

-- 10. SEGURO BET - Complete Information
((SELECT id FROM casinos WHERE slug = 'seguro-bet'), 'en',
    'Seguro Bet Brasil Ltda', '2023', 'Brazilian License Application', 'Brazil',
    'BRL', 'Portuguese', 'Sports Betting, Casino',
    'PIX, Bank Transfer', 'Mobile Web', 'Portuguese Support',
    'Focus on security and responsible gaming, Brazilian owned',
    'Sports betting with focus on Brazilian leagues, basic casino games',
    'Applied for Brazilian federal license, pending approval',
    'Exclusively targets Brazilian market',
    'Football, basketball, volleyball, tennis, basic slots',
    'Pre-match and live betting, Brazilian championship focus',
    'Modest welcome bonus, occasional promotions',
    'Suitable for conservative Brazilian bettors prioritizing security'
),
((SELECT id FROM casinos WHERE slug = 'seguro-bet'), 'pt',
    'Seguro Bet Brasil Ltda', '2023', 'Solicitação de Licença Brasileira', 'Brasil',
    'BRL', 'Português', 'Apostas Esportivas, Cassino',
    'PIX, Transferência Bancária', 'Web Mobile', 'Suporte em Português',
    'Foco em segurança e jogo responsável, propriedade brasileira',
    'Apostas esportivas com foco em ligas brasileiras, jogos básicos de cassino',
    'Solicitou licença federal brasileira, aprovação pendente',
    'Exclusivamente direcionado ao mercado brasileiro',
    'Futebol, basquete, vôlei, tênis, slots básicos',
    'Apostas pré-jogo e ao vivo, foco em campeonatos brasileiros',
    'Bônus de boas-vindas modesto, promoções ocasionais',
    'Adequado para apostadores brasileiros conservadores que priorizam segurança'
),
((SELECT id FROM casinos WHERE slug = 'seguro-bet'), 'zh',
    'Seguro Bet Brasil Ltda', '2023', '巴西許可證申請', '巴西',
    'BRL', '葡萄牙語', '體育博彩、賭場',
    'PIX、銀行轉帳', '移動網頁', '葡萄牙語支援',
    '專注於安全和負責任遊戲、巴西擁有',
    '體育博彩專注於巴西聯賽、基本賭場遊戲',
    '已申請巴西聯邦許可證、待批准',
    '專門針對巴西市場',
    '足球、籃球、排球、網球、基本老虎機',
    '賽前和滾球投注、專注巴西錦標賽',
    '適度的歡迎獎金、偶爾的促銷',
    '適合重視安全的保守巴西投注者'
),

-- 11. BATEU BET - Complete Information
((SELECT id FROM casinos WHERE slug = 'bateu-bet'), 'en',
    'Bateu Bet Entertainment', '2023', 'Brazilian License Pending', 'Brazil',
    'BRL', 'Portuguese', 'Sports, Casino',
    'PIX', 'Mobile Optimized', 'Email Support',
    'New Brazilian platform, simple interface, quick payouts',
    'Focus on major sports, growing casino section',
    'Operating while license application is processed',
    'Brazil exclusive',
    'Football, basketball, tennis, growing slot selection',
    'Basic live betting, pre-match markets',
    'New player bonuses, periodic promotions',
    'Good for beginners and casual Brazilian players'
),
((SELECT id FROM casinos WHERE slug = 'bateu-bet'), 'pt',
    'Bateu Bet Entertainment', '2023', 'Licença Brasileira Pendente', 'Brasil',
    'BRL', 'Português', 'Esportes, Cassino',
    'PIX', 'Otimizado para Mobile', 'Suporte por Email',
    'Nova plataforma brasileira, interface simples, pagamentos rápidos',
    'Foco em esportes principais, seção de cassino em crescimento',
    'Operando enquanto a solicitação de licença é processada',
    'Exclusivo Brasil',
    'Futebol, basquete, tênis, seleção crescente de slots',
    'Apostas ao vivo básicas, mercados pré-jogo',
    'Bônus para novos jogadores, promoções periódicas',
    'Bom para iniciantes e jogadores brasileiros casuais'
),
((SELECT id FROM casinos WHERE slug = 'bateu-bet'), 'zh',
    'Bateu Bet Entertainment', '2023', '巴西許可證待定', '巴西',
    'BRL', '葡萄牙語', '體育、賭場',
    'PIX', '移動優化', '電子郵件支援',
    '新的巴西平台、簡單界面、快速支付',
    '專注於主要體育、成長中的賭場部分',
    '在處理許可證申請時運營',
    '巴西專屬',
    '足球、籃球、網球、成長中的老虎機選擇',
    '基本滾球投注、賽前市場',
    '新玩家獎金、定期促銷',
    '適合初學者和休閒巴西玩家'
),

-- 12. BRAZINO777 - Complete Information
((SELECT id FROM casinos WHERE slug = 'brazino777'), 'en',
    'Brazino777 N.V.', '2018', 'Curacao License', 'Brazil, Latin America',
    'BRL, USD, EUR, BTC', 'Portuguese, English, Spanish', 'Casino, Sports, Live Casino',
    'PIX, Boleto, Cards, Crypto', 'Android, iOS', '24/7 Live Chat',
    'Brazil-themed casino, huge game selection, crypto support',
    'Over 4000 casino games, sports betting, live dealers, tournaments',
    'Curacao eGaming License (8048/JAZ)',
    'Focused on Brazil and Latin American markets',
    'Slots, table games, live casino, sports betting, poker',
    'Live betting, virtual sports, tournament play, jackpots',
    'Welcome package up to R$4000, weekly bonuses, VIP program',
    'Ideal for casino enthusiasts and players seeking variety'
),
((SELECT id FROM casinos WHERE slug = 'brazino777'), 'pt',
    'Brazino777 N.V.', '2018', 'Licença Curaçao', 'Brasil, América Latina',
    'BRL, USD, EUR, BTC', 'Português, Inglês, Espanhol', 'Cassino, Esportes, Cassino ao Vivo',
    'PIX, Boleto, Cartões, Cripto', 'Android, iOS', 'Chat ao Vivo 24/7',
    'Cassino com tema brasileiro, enorme seleção de jogos, suporte a cripto',
    'Mais de 4000 jogos de cassino, apostas esportivas, dealers ao vivo, torneios',
    'Licença Curacao eGaming (8048/JAZ)',
    'Focado no Brasil e mercados da América Latina',
    'Slots, jogos de mesa, cassino ao vivo, apostas esportivas, pôquer',
    'Apostas ao vivo, esportes virtuais, torneios, jackpots',
    'Pacote de boas-vindas até R$4000, bônus semanais, programa VIP',
    'Ideal para entusiastas de cassino e jogadores que buscam variedade'
),
((SELECT id FROM casinos WHERE slug = 'brazino777'), 'zh',
    'Brazino777 N.V.', '2018', '庫拉索許可證', '巴西、拉丁美洲',
    'BRL, USD, EUR, BTC', '葡萄牙語、英語、西班牙語', '賭場、體育、真人賭場',
    'PIX、Boleto、卡片、加密貨幣', 'Android、iOS', '24/7即時聊天',
    '巴西主題賭場、龐大遊戲選擇、加密支援',
    '超過4000個賭場遊戲、體育博彩、真人荷官、錦標賽',
    '庫拉索電子遊戲許可證（8048/JAZ）',
    '專注於巴西和拉丁美洲市場',
    '老虎機、桌上遊戲、真人賭場、體育博彩、撲克',
    '滾球投注、虛擬體育、錦標賽遊戲、頭獎',
    '歡迎套餐高達R$4000、每週獎金、VIP計劃',
    '適合賭場愛好者和尋求多樣性的玩家'
);

-- Add some default player type associations (can be modified in admin panel)
-- Associate sports-focused casinos with sports betting player type
INSERT OR IGNORE INTO player_type_casinos (player_type_id, casino_id, sort_order)
SELECT 
    (SELECT id FROM player_types WHERE name_en LIKE '%Sport%' OR name_en LIKE '%sport%' LIMIT 1),
    id,
    ROW_NUMBER() OVER (ORDER BY name)
FROM casinos 
WHERE slug IN ('bet365', 'betano', 'betwinner', '22bet', '1xbet', 'estrela-bet');

-- Associate casino-focused platforms with casino player type
INSERT OR IGNORE INTO player_type_casinos (player_type_id, casino_id, sort_order)
SELECT 
    (SELECT id FROM player_types WHERE name_en LIKE '%Casino%' OR name_en LIKE '%casino%' LIMIT 1),
    id,
    ROW_NUMBER() OVER (ORDER BY name)
FROM casinos 
WHERE slug IN ('brazino777', 'blaze', '22bet', 'betwinner', '1xbet');

-- Associate beginner-friendly platforms
INSERT OR IGNORE INTO player_type_casinos (player_type_id, casino_id, sort_order)
SELECT 
    (SELECT id FROM player_types WHERE name_en LIKE '%Begin%' OR name_en LIKE '%New%' LIMIT 1),
    id,
    ROW_NUMBER() OVER (ORDER BY name)
FROM casinos 
WHERE slug IN ('betano', 'estrela-bet', 'bateu-bet', 'seguro-bet');

-- Add sample blog posts about Brazilian casinos
INSERT OR IGNORE INTO blog_posts (
    category_id, slug, title_en, title_pt, title_zh,
    excerpt_en, excerpt_pt, excerpt_zh,
    content_en, content_pt, content_zh,
    featured_image, author, is_published, published_at
) VALUES
(
    (SELECT id FROM blog_categories WHERE slug = 'guides' LIMIT 1),
    'brazil-online-betting-guide-2024',
    'Complete Guide to Online Betting in Brazil 2024',
    'Guia Completo de Apostas Online no Brasil 2024',
    '2024年巴西線上博彩完整指南',
    'Everything you need to know about legal online betting in Brazil',
    'Tudo o que você precisa saber sobre apostas online legais no Brasil',
    '關於巴西合法線上博彩您需要知道的一切',
    'Brazil has recently legalized and regulated online betting, creating exciting opportunities for players. This comprehensive guide covers the new regulations, best licensed operators, payment methods like PIX, and responsible gaming practices. Learn about the top platforms including Bet365, Betano, and local favorites like EstrelaBet.',
    'O Brasil recentemente legalizou e regulamentou as apostas online, criando oportunidades empolgantes para os jogadores. Este guia abrangente cobre as novas regulamentações, melhores operadores licenciados, métodos de pagamento como PIX e práticas de jogo responsável. Conheça as principais plataformas incluindo Bet365, Betano e favoritos locais como EstrelaBet.',
    '巴西最近將線上博彩合法化並進行監管，為玩家創造了令人興奮的機會。這份綜合指南涵蓋了新規定、最佳持牌運營商、PIX等支付方式以及負責任的遊戲實踐。了解包括Bet365、Betano和EstrelaBet等本地熱門平台。',
    '/images/blog/brazil-betting-guide.jpg',
    'Editorial Team',
    1,
    datetime('now', '-2 days')
),
(
    (SELECT id FROM blog_categories WHERE slug = 'news' LIMIT 1),
    'pix-payment-revolution-brazil',
    'How PIX Revolutionized Online Casino Payments in Brazil',
    'Como o PIX Revolucionou os Pagamentos em Cassinos Online no Brasil',
    'PIX如何革新巴西線上賭場支付',
    'Instant payments with PIX have transformed the Brazilian betting landscape',
    'Pagamentos instantâneos com PIX transformaram o cenário de apostas brasileiro',
    'PIX即時支付改變了巴西博彩業格局',
    'PIX has become the preferred payment method for Brazilian bettors, offering instant deposits and withdrawals. This article explores how PIX integration has boosted the online betting industry in Brazil, with platforms like Betwinner, 22Bet, and Blaze leading the adoption.',
    'O PIX se tornou o método de pagamento preferido dos apostadores brasileiros, oferecendo depósitos e saques instantâneos. Este artigo explora como a integração do PIX impulsionou a indústria de apostas online no Brasil, com plataformas como Betwinner, 22Bet e Blaze liderando a adoção.',
    'PIX已成為巴西投注者首選的支付方式，提供即時存款和提款。本文探討了PIX整合如何推動巴西線上博彩業的發展，Betwinner、22Bet和Blaze等平台引領了這一趨勢。',
    '/images/blog/pix-payment.jpg',
    'Financial Expert',
    1,
    datetime('now', '-5 days')
);